apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Sayan
spec:
  profile:
    displayName: Sayan Saha
    email: sayansaha08.02.90@gmail.com
kind: Component
metadata:
  name: assignment-sc
  title: Assignment on Angular and Docker for SC
  description: |
    Dockerized application of Angular for assignment
  annotations:
    github.com/project-slug: Sayan007/assignment
  tags:
    - angular
    - js
    - docker
spec:
  type: service
  owner: user:Sayan
  lifecycle: development
